# Generated by Django 5.1.4 on 2025-01-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('color', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='cars/')),
                ('category', models.IntegerField(choices=[(0, 'Sedan'), (1, 'SUV'), (2, 'Electric'), (3, 'Coupe')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, 'Sedan'), (1, 'SUV'), (2, 'Electric'), (3, 'Coupe')], default=0, max_length=100)),
            ],
        ),
    ]
